### ISSUE TITLE
pip nor conda cannot install hiddenlayer

### ISSUE THREAD

**Issue by sonsus** [waleedka/hiddenlayer#34]
pip 18.0
conda 4.6.11
ubuntu 16.04
nv-docker2 

> conda install graphviz python-graphviz 

> conda list
```
# Name                    Version                   Build  Channel
_tflow_select             2.1.0                       gpu  
absl-py                   0.7.1                    py36_0    conda-forge
asn1crypto                0.24.0                py36_1003    conda-forge
astor                     0.7.1                      py_0    conda-forge
backcall                  0.1.0                      py_0    conda-forge
binutils_impl_linux-64    2.31.1               h6176602_1    conda-forge
binutils_linux-64         2.31.1               h6176602_3    conda-forge
blas                      1.0                         mkl  
bleach                    2.1.4                      py_1    conda-forge
blinker                   1.4                        py_1    conda-forge
boto                      2.49.0                   py36_0  
boto3                     1.9.53                     py_0    conda-forge
botocore                  1.12.54                    py_0    conda-forge
bz2file                   0.98                       py_0    conda-forge
bzip2                     1.0.6                h470a237_2    conda-forge
c-ares                    1.15.0            h14c3975_1001    conda-forge
ca-certificates           2019.3.9             hecc5488_0    conda-forge
cairo                     1.16.0            ha4e643d_1000    conda-forge
certifi                   2019.3.9                 py36_0    conda-forge
cffi                      1.11.5           py36h5e8e0c9_1    conda-forge
chardet                   3.0.4                 py36_1003    conda-forge
cryptography              2.6.1            py36h9d9f1b6_0    conda-forge
cryptography-vectors      2.3.1                 py36_1000    conda-forge
cudatoolkit               9.0                  h13b8566_0  
cudnn                     7.3.1                 cuda9.0_0  
cupti                     9.0.176                       0  
curl                      7.64.0               h646f8bb_2    conda-forge
cycler                    0.10.0                     py_1    conda-forge
dbus                      1.13.0               h3a4f0e9_0    conda-forge
decorator                 4.3.0                      py_0    conda-forge
docutils                  0.14                  py36_1001    conda-forge
entrypoints               0.2.3                    py36_2    conda-forge
expat                     2.2.5                hfc679d8_2    conda-forge
fontconfig                2.13.1               h65d0f4c_0    conda-forge
freetype                  2.9.1                h6debe1e_4    conda-forge
gast                      0.2.2                      py_0    conda-forge
gcc_impl_linux-64         7.3.0                habb00fd_1    conda-forge
gcc_linux-64              7.3.0                h553295d_3    conda-forge
gensim                    3.5.0                    py36_0    conda-forge
gettext                   0.19.8.1             h5e8e0c9_1    conda-forge
git                       2.21.0          pl526h2882143_0    conda-forge
glib                      2.58.3            hf63aee3_1001    conda-forge
gmp                       6.1.2                hfc679d8_0    conda-forge
graphite2                 1.3.13            hf484d3e_1000    conda-forge
graphviz                  2.40.1               h0dab3d1_0    conda-forge
grpcio                    1.16.1           py36hf8bcb03_1  
gst-plugins-base          1.14.4            hdf3bae2_1001    conda-forge
gstreamer                 1.14.4            h66beb1c_1001    conda-forge
gxx_impl_linux-64         7.3.0                hdf63c60_1    conda-forge
gxx_linux-64              7.3.0                h553295d_3    conda-forge
h5py                      2.9.0           nompi_py36hf008753_1102    conda-forge
harfbuzz                  2.3.1                h6824563_0    conda-forge
hdf5                      1.10.4          nompi_h11e915b_1105    conda-forge
html5lib                  1.0.1                      py_0    conda-forge
icu                       58.2                 hfc679d8_0    conda-forge
idna                      2.7                   py36_1002    conda-forge
intel-openmp              2019.1                      144  
ipykernel                 5.0.0              pyh24bf2e0_1    conda-forge
ipython                   7.0.1            py36h24bf2e0_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.4.2                      py_0    conda-forge
jedi                      0.12.1                   py36_0    conda-forge
jinja2                    2.10                       py_1    conda-forge
jmespath                  0.9.3                      py_1    conda-forge
jpeg                      9c                   h470a237_1    conda-forge
jsonschema                2.6.0                    py36_2    conda-forge
jupyter                   1.0.0                      py_1    conda-forge
jupyter_client            5.2.3                      py_1    conda-forge
jupyter_console           5.1.0                    py36_0    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
jupyterlab                0.34.12                  py36_0    conda-forge
jupyterlab_launcher       0.13.1                     py_2    conda-forge
keras                     2.1.6                    py36_0    conda-forge
keras-applications        1.0.7                      py_0    conda-forge
keras-preprocessing       1.0.9                      py_0    conda-forge
kiwisolver                1.0.1            py36h2d50403_2    conda-forge
krb5                      1.16.3            h05b26f9_1001    conda-forge
libcurl                   7.64.0               h541490c_2    conda-forge
libedit                   3.1.20170329         haf1bffa_1    conda-forge
libffi                    3.2.1                hfc679d8_5    conda-forge
libgcc-ng                 7.3.0                hdf63c60_0    conda-forge
libgfortran               3.0.0                         1    conda-forge
libgfortran-ng            7.2.0                hdf63c60_3    conda-forge
libgpuarray               0.7.6             h14c3975_1003    conda-forge
libiconv                  1.15                 h470a237_3    conda-forge
libpng                    1.6.35               ha92aebf_2    conda-forge
libprotobuf               3.7.0                h8b12597_2    conda-forge
libsodium                 1.0.16               h470a237_1    conda-forge
libssh2                   1.8.0             h90d6eec_1004    conda-forge
libstdcxx-ng              7.3.0                hdf63c60_0    conda-forge
libtiff                   4.0.9                he6b73bb_2    conda-forge
libtool                   2.4.6             h14c3975_1002    conda-forge
libuuid                   2.32.1               h470a237_2    conda-forge
libxcb                    1.13                 h470a237_2    conda-forge
libxml2                   2.9.8                h422b904_5    conda-forge
mako                      1.0.7                      py_1    conda-forge
markdown                  2.6.11                     py_0    conda-forge
markupsafe                1.0              py36h470a237_1    conda-forge
matplotlib                3.0.3                    py36_0    conda-forge
matplotlib-base           3.0.3            py36h167e16e_0    conda-forge
mistune                   0.8.3            py36h470a237_2    conda-forge
mkl                       2018.0.3                      1  
mkl_fft                   1.0.10                   py36_0    conda-forge
mkl_random                1.0.2                    py36_0    conda-forge
nb_conda_kernels          2.1.1                    py36_1    conda-forge
nbconvert                 5.3.1                      py_1    conda-forge
nbformat                  4.4.0                      py_1    conda-forge
ncurses                   6.1                  hfc679d8_1    conda-forge
ninja                     1.8.2                h2d50403_1    conda-forge
nltk                      3.2.5                      py_0    conda-forge
notebook                  5.7.0                    py36_0    conda-forge
numpy                     1.15.0           py36h1b885b7_0  
numpy-base                1.15.0           py36h3dfced4_0  
oauthlib                  2.1.0                      py_0    conda-forge
olefile                   0.46                       py_0    conda-forge
openblas                  0.2.20                        8    conda-forge
openssl                   1.1.1b               h14c3975_1    conda-forge
pandas                    0.23.4           py36hf8a1672_0    conda-forge
pandoc                    2.3.1                         0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
pango                     1.40.14           h4ea9474_1004    conda-forge
parso                     0.3.1                      py_0    conda-forge
pcre                      8.41                 hfc679d8_3    conda-forge
perl                      5.26.2               h470a237_0    conda-forge
pexpect                   4.6.0                    py36_0    conda-forge
pickleshare               0.7.5                    py36_0    conda-forge
pillow                    5.3.0            py36hc736899_0    conda-forge
pip                       18.0                     py36_1    conda-forge
pixman                    0.34.0            h14c3975_1003    conda-forge
prometheus_client         0.3.1                      py_1    conda-forge
prompt_toolkit            2.0.5                      py_0    conda-forge
protobuf                  3.7.0            py36he1b5a44_1    conda-forge
pthread-stubs             0.4                  h470a237_1    conda-forge
ptyprocess                0.6.0                 py36_1000    conda-forge
pycparser                 2.19                       py_0    conda-forge
pygments                  2.2.0                      py_1    conda-forge
pygpu                     0.7.6           py36h3010b51_1000    conda-forge
pyjwt                     1.6.4                      py_0    conda-forge
pyopenssl                 18.0.0                py36_1000    conda-forge
pyparsing                 2.3.0                      py_0    conda-forge
pyqt                      4.11.4                   py36_3    conda-forge
pysocks                   1.6.8                 py36_1002    conda-forge
python                    3.6.7                h0371630_0  
python-crfsuite           0.9.6            py36h2d50403_0    conda-forge
python-dateutil           2.7.3                      py_0    conda-forge
python-graphviz           0.10.1                     py_0    conda-forge
pytorch                   1.0.1           py3.6_cuda9.0.176_cudnn7.4.2_0    pytorch
pytz                      2018.5                     py_0    conda-forge
pyyaml                    5.1              py36h14c3975_0    conda-forge
pyzmq                     17.1.2           py36hae99301_0    conda-forge
qt                        4.8.7                         2  
qtconsole                 4.4.1                    py36_1    conda-forge
readline                  7.0                  haf1bffa_1    conda-forge
requests                  2.20.1                py36_1000    conda-forge
requests-oauthlib         1.0.0                      py_1    conda-forge
s3transfer                0.1.13                py36_1001    conda-forge
scikit-learn              0.19.1           py36hedc7406_0  
scipy                     1.1.0            py36hc49cb51_0  
send2trash                1.5.0                      py_0    conda-forge
setuptools                40.4.0                py36_1000    conda-forge
simplegeneric             0.8.1                      py_1    conda-forge
sip                       4.18                     py36_1    conda-forge
six                       1.11.0                   py36_1    conda-forge
smart_open                1.7.1                      py_0    conda-forge
sqlite                    3.25.2               hb1c47c0_0    conda-forge
tensorboard               1.12.0                py36_1000    conda-forge
tensorboardx              1.6                        py_0    conda-forge
tensorflow                1.12.0          gpu_py36he68c306_0  
tensorflow-base           1.12.0          gpu_py36h8e0ae2d_0  
tensorflow-gpu            1.12.0               h0d30ee6_0  
termcolor                 1.1.0                      py_2    conda-forge
terminado                 0.8.1                    py36_1    conda-forge
testpath                  0.4.1                    py36_0    conda-forge
theano                    1.0.4           py36hf484d3e_1000    conda-forge
tk                        8.6.9                ha92aebf_0    conda-forge
torchvision               0.2.1                      py_2    pytorch
tornado                   5.1.1            py36h470a237_0    conda-forge
traitlets                 4.3.2                    py36_0    conda-forge
twython                   3.7.0                      py_0    conda-forge
urllib3                   1.23                  py36_1001    conda-forge
wcwidth                   0.1.7                      py_1    conda-forge
webencodings              0.5.1                      py_1    conda-forge
werkzeug                  0.14.1                     py_0    conda-forge
wheel                     0.31.1                py36_1001    conda-forge
widgetsnbextension        3.4.2                    py36_0    conda-forge
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libice               1.0.9             h516909a_1004    conda-forge
xorg-libsm                1.2.3             h84519dc_1000    conda-forge
xorg-libx11               1.6.7             h14c3975_1000    conda-forge
xorg-libxau               1.0.8                h470a237_6    conda-forge
xorg-libxdmcp             1.1.2                h470a237_7    conda-forge
xorg-libxext              1.3.4                h516909a_0    conda-forge
xorg-libxpm               3.5.12            h14c3975_1002    conda-forge
xorg-libxrender           0.9.10            h516909a_1002    conda-forge
xorg-libxt                1.1.5             h14c3975_1002    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h14c3975_1007    conda-forge
xz                        5.2.4                h470a237_1    conda-forge
yaml                      0.1.7             h14c3975_1001    conda-forge
zeromq                    4.2.5                hfc679d8_6    conda-forge
zlib                      1.2.11               h470a237_3    conda-forge
(dl) root@dab3b36995ff:/workhere/hiddenlayer# 

```
> pip install hiddenlayer 
or
> clone from github (as shown in the README.md, developer mode) 
both results in **error:**
```
Exception:
Traceback (most recent call last):
  File "/root/anaconda3/envs/dl/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2869, in _dep_map
    return self.__dep_map
  File "/root/anaconda3/envs/dl/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2663, in __getattr__
    raise AttributeError(attr)
AttributeError: _DistInfoDistribution__dep_map

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/anaconda3/envs/dl/lib/python3.6/site-packages/pip/_vendor/packaging/requirements.py", line 93, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "/root/anaconda3/envs/dl/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 1632, in parseString
    raise exc
  File "/root/anaconda3/envs/dl/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 1622, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "/root/anaconda3/envs/dl/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/root/anaconda3/envs/dl/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 3395, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/root/anaconda3/envs/dl/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 1383, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/root/anaconda3/envs/dl/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 3183, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pip._vendor.pyparsing.ParseException: Expected stringEnd (at char 33), (line:1, col:34)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/anaconda3/envs/dl/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2949, in __init__
    super(Requirement, self).__init__(requirement_string)
  File "/root/anaconda3/envs/dl/lib/python3.6/site-packages/pip/_vendor/packaging/requirements.py", line 97, in __init__
    requirement_string[e.loc:e.loc + 8]))
pip._vendor.packaging.requirements.InvalidRequirement: Invalid requirement, parse error at "'; extra '"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/anaconda3/envs/dl/lib/python3.6/site-packages/pip/_internal/basecommand.py", line 141, in main
    status = self.run(options, args)
  File "/root/anaconda3/envs/dl/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 330, in run
    self._warn_about_conflicts(to_install)
  File "/root/anaconda3/envs/dl/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 456, in _warn_about_conflicts
    package_set, _dep_info = check_install_conflicts(to_install)
  File "/root/anaconda3/envs/dl/lib/python3.6/site-packages/pip/_internal/operations/check.py", line 98, in check_install_conflicts
    package_set = create_package_set_from_installed()
  File "/root/anaconda3/envs/dl/lib/python3.6/site-packages/pip/_internal/operations/check.py", line 41, in create_package_set_from_installed
    package_set[name] = PackageDetails(dist.version, dist.requires())
  File "/root/anaconda3/envs/dl/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2607, in requires
    dm = self._dep_map
  File "/root/anaconda3/envs/dl/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2871, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/root/anaconda3/envs/dl/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2881, in _compute_dependencies
    reqs.extend(parse_requirements(req))
  File "/root/anaconda3/envs/dl/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2942, in parse_requirements
    yield Requirement(line)
  File "/root/anaconda3/envs/dl/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2951, in __init__
    raise RequirementParseError(str(e))
pip._vendor.pkg_resources.RequirementParseError: Invalid requirement, parse error at "'; extra '"
```

**Comment by dSciJason** [comment]
I was having a similar issue but found that you need to create a python environment in anaconda, switch to it in a terminal, and then pip in hiddenlayer

Reference
https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html

**Comment by sonsus** [comment]
@dSciJason I'm already using it and my conda env with pytorch cannot install it via pip nor conda. That is the problem. It'll probably work if I start from the empty environment to install this but I don't want to make a whole new environment from the scratch to use this.
