### ISSUE TITLE
build_graph() does not return

### ISSUE THREAD

**Issue by buttercutter** [waleedka/hiddenlayer#90]
I tried to use `hiddenlayer` on this [network architecture search coding](https://gist.github.com/promach/b6f526c56e20f029d68e6f9041c3f5c0#file-gdas-py-L423-L434) for the following [search architecture](https://github.com/D-X-Y/AutoDL-Projects/issues/99#issuecomment-835802887), however the code could not exit and is inside `build_graph()` forever.

![image](https://user-images.githubusercontent.com/3324659/133936254-dbd4a26d-6650-455d-8083-77086f70e03c.png)

**Comment by buttercutter** [comment]
I used this `hl.build_graph(graph(train_inputs), torch.zeros([1, 3, 32, 32]).cuda())` instead and `hiddenlayer` gave me the following error:

```
Traceback (most recent call last):
  File "/home/phung/PycharmProjects/beginner_tutorial/gdas.py", line 793, in <module>
    ltrain = train_NN(forward_pass_only=0)
  File "/home/phung/PycharmProjects/beginner_tutorial/gdas.py", line 429, in train_NN
    hl.build_graph(graph(train_inputs), torch.zeros([1, 3, 32, 32]).cuda())
  File "/usr/lib/python3.9/site-packages/hiddenlayer/graph.py", line 148, in build_graph
    raise ValueError("`model` input param must be a PyTorch, TensorFlow, or Keras-with-TensorFlow-backend model.") 
ValueError: `model` input param must be a PyTorch, TensorFlow, or Keras-with-TensorFlow-backend model.
```

**Comment by dasdristanta13** [comment]
I think within the graph() you should not pass the train_inputs. Try without giving the train_inputs, i.e, try this instead,
`
hl.build_graph(graph(), torch.zeros([1, 3, 32, 32]).cuda())
`
